name: rna_design_optim
channels:
  - conda-forge
dependencies:
  - python=3.9  # Change to your desired Python version
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - matplotlib
  - notebook
  - jupyterlab
  - scipy
  - pytz
  - h5py
  - pillow
  - seaborn
  - protobuf
  - grpcio
  - ipykernel
  - ipywidgets
  - jinja2
  - tqdm
  - pip
  - pip:
    - absl-py==2.1.0
    - anyio==4.0.0
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - attrs==22.2.0
    - Babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - biopython==1.83
    - bleach==4.1.0
    - Brotli==1.0.9
    - cachetools==5.3.3
    - cffi==1.15.0
    - chardet==5.2.0
    - charset-normalizer==3.0.0
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - configparser==6.0.1
    - contourpy==1.2.0
    - csvsort==1.6.1
    - cycler==0.12.1
    - Cython==3.0.8
    - dask==2024.2.1
    - defusedxml==0.7.1
    - Distance==0.1.3
    - distlib==0.3.6
    - et-xmlfile==1.1.0
    - executing==2.0.1
    - filelock==3.13.1
    - flatbuffers==23.5.26
    - fonttools==4.50.0
    - forgi==2.0.2
    - fqdn==1.5.1
    - fsspec==2024.2.0
    - future==0.18.3
    - gast==0.5.4
    - gdown==4.6.4
    - google-auth==2.19.1
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - GraKeL==0.1.9
    - grpcio==1.62.0
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.22.2
    - icecream==2.1.3
    - idna==3.4
    - importlib-metadata==7.0.0
    - importlib_resources==6.4.0
    - iniconfig==2.0.0
    - ipykernel==6.24.0
    - ipython==8.18.0
    - isoduration==20.11.0
    - jedi==0.19.0
    - Jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jupyter==1.0.0
    - jupyter-console==6.6.0
    - jupyter-events==0.10.0
    - jupyter_client==8.2.0
    - jupyter_core==5.1.0
    - jupyter_server==2.10.0
    - jupyter_server_terminals==0.5.1
    - jupyterlab==4.0.10
    - jupyterlab-pygments==0.2.2
    - jupyterlab_server==2.21.0
    - keras==2.15.0
    - Markdown==3.5.2
    - MarkupSafe==2.1.3
    - matplotlib==3.8.3
    - mistune==2.0.0
    - ml-dtypes==0.2.0
    - nbclient==0.10.0
    - nbconvert==7.10.0
    - nbformat==5.10.4
    - nest-asyncio==1.5.7
    - networkx==3.2.1
    - nltk==3.8.1
    - notebook==7.1.0
    - numpy==1.23.5
    - oauthlib==3.2.2
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - packaging==24.0.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - partd==1.4.1
    - pickleshare==0.7.5
    - pillow==10.2.0
    - plotly==5.19.0
    - pluggy==1.4.0
    - ply==3.11
    - progressbar2==4.4.2
    - prometheus-client==0.18.0
    - prompt-toolkit==3.0.39
    - protobuf==4.25.3
    - psutil==5.9.4
    - pyaml==21.10.1
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - Pygments==2.15.0
    - pynisher==1.0.2
    - pyparsing==3.1.2
    - PyQt5==5.15.10
    - PySocks==1.7.1
    - pytest==8.0.2
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-utils==3.8.2
    - PyYAML==6.0.1
    - QtPy==2.3.0
    - referencing==0.30.0
    - regex==2022.10.31
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rna-tools==3.20.3
    - RnaBench==0.1.2
    - rsa==4.9
    - safetensors==0.4.3
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - simplejson==3.19.2
    - sip==6.7.0
    - six==1.16.0
    - stack-data==0.6.1
    - svgwrite==1.4.3
    - tenacity==8.2.3
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - tokenizers==0.15.2
    - tomli==2.0.1
    - torch==1.13.1
    - torchvision==0.14.1
    - tornado==6.3.3
    - tqdm==4.66.2
    - transformers==4.39.3
    - urllib3==1.26.18
    - ViennaRNA==2.6.4
    - Werkzeug==3.0.1
    - wget==3.2
    - wrapt==1.14.1
    - zipp==3.16.0
