version: '1.0'

services:
  rl:
    build:
      context: /RNA_Design_RL
      dockerfile: RNA_Design_RL.dockerfile
    volumes:
      - ./rl:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "6000:6000" 
    working_dir: /app

  optim:
    build:
      context: /RNA_Design_Optim
      dockerfile: RNA_Design_Optim.dockerfile
    volumes:
      - ./optim:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "6001:6001"
    working_dir: /app

      rl:
    build:
      context: /RNA_Design_ANTARNA
      dockerfile: RNA_Design_ANTARNA.dockerfile
    volumes:
      - ./rl:/app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "6002:6002" 
    working_dir: /app
